name: main

on:
  schedule:
    - cron: "0 15 * * *" # runs every day at 3pm

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout predictit-bot
        uses: actions/checkout@v2
        with:
          repository: dalton-b/predictit-bot
          path: predictit-bot
      - name: Checkout dbdotcom
        uses: actions/checkout@v2
        with:
          repository: dalton-b/dbdotcom
          path: dbdotcom
      - name: Copy html to dbdotcom
        run: |
          cp predictit-bot/requirements.txt dbdotcom
          cd dbdotcom
          git config --local user.name "dalton-b"
          git add .
          git commit -m "predictit-bot daily update" -a
      - name: Push changes to dbdotcom
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          directory: dbdotcom
          repository: dalton-b/dbdotcom
